/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import dao.DAO_XeMay;
import entity.NhanVien;
import entity.XeMay;

/**
 *
 * @author Lenovo
 */
public class BanHangFrame extends javax.swing.JFrame {
	List<XeMay> listXeMay;
	DefaultTableModel tableModel;
	DAO_XeMay dao_xeMay = new DAO_XeMay();
	String path = "";
	NumberFormat formatter = new DecimalFormat("#0.00");
	private int maXe;
	private NhanVien nhanVien;

    /**
     * Creates new form BanHangFrame
     */
    public BanHangFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        tableModel = (DefaultTableModel) tableXeMay.getModel();
        showData();
        loadDetailXe(listXeMay.get(0).getMaXe());
    }
    public BanHangFrame(NhanVien nhanVien) {
        initComponents();
        setLocationRelativeTo(null);
        tableModel = (DefaultTableModel) tableXeMay.getModel();
        showData();
        loadDetailXe(listXeMay.get(0).getMaXe());
        this.nhanVien = nhanVien;
    }

    private void showData() {
    	listXeMay = dao_xeMay.getDanhSachXeMay();
    	tableModel.setRowCount(0);
    	for(XeMay item: listXeMay) {
    		tableModel.addRow(new Object[] {item.getLoaiXe().getTenLoai(), item.getMaXe(), item.getTenXe(), item.getSoPK(),item.getMauXe(),item.getNuocSanXuat(),formatter.format(item.getDongia())});
    	}
    }
    private void loadDetailXe(int maXe) {
    	this.maXe = maXe;
    	XeMay xeMay = dao_xeMay.getXeMayByMaXe(maXe);
    	lblTenXe.setText(xeMay.getTenXe());
    	lblGiaXe.setText("Giá : "+ formatter.format(xeMay.getDongia()));
    	lblLoaiXe.setText("Loại xe: "+ xeMay.getLoaiXe().getTenLoai());
    	lblSoPK.setText("Số phân khối: "+String.valueOf(xeMay.getSoPK())+" cc");
    	lblMauXe.setText("Màu xe: " + xeMay.getMauXe());
    	lblNuocSanXuat.setText("Nước sản xuất: "+xeMay.getNuocSanXuat());
    	try {
    		path = dao_xeMay.getImage(maXe);
    		ImageIcon icon = new ImageIcon(path);
			Image img = icon.getImage();
			Image newImg = img.getScaledInstance(labelHinhAnh.getWidth(), labelHinhAnh.getHeight(), Image.SCALE_SMOOTH);
			ImageIcon imgIcon = new ImageIcon(newImg);
			labelHinhAnh.setIcon(imgIcon);
    	}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
    private void clickItemtable() {
    	int index = tableXeMay.getSelectedRow();
    	loadDetailXe(listXeMay.get(index).getMaXe());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableXeMay = new javax.swing.JTable();
        labelHinhAnh = new javax.swing.JLabel();
        lblTenXe = new javax.swing.JLabel();
        lblGiaXe = new javax.swing.JLabel();
        lblLoaiXe = new javax.swing.JLabel();
        lblSoPK = new javax.swing.JLabel();
        lblMauXe = new javax.swing.JLabel();
        lblNuocSanXuat = new javax.swing.JLabel();
        btnTaoHopDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bán Hàng");

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tableXeMay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên loại", "Mã xe", "Tên xe", "Số phân khối", "Màu xe", "Nước sản xuất", "Đơn giá"
            }
        ));
        jScrollPane1.setViewportView(tableXeMay);

        labelHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHinhAnh.setText("Ảnh");
        labelHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTenXe.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTenXe.setText("Vision (Phiên bản Cá tính)");

        lblGiaXe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGiaXe.setForeground(new java.awt.Color(255, 51, 0));
        lblGiaXe.setText("Giá : 1000000000 VND");

        lblLoaiXe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLoaiXe.setText("Loại xe: Xe tay ga");

        lblSoPK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSoPK.setText("Số phân khối: 500 cc");

        lblMauXe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMauXe.setText("Màu xe: Đỏ");

        lblNuocSanXuat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNuocSanXuat.setText("Nước sản xuất: Trung Quốc");

        btnTaoHopDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-contract-20.png"))); // NOI18N
        btnTaoHopDong.setText("Tạo Hợp Đồng");
        
        tableXeMay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCNNCCMouseClicked(evt);
            }

			private void tableCNNCCMouseClicked(MouseEvent evt) {
				// TODO Auto-generated method stub
				clickItemtable();
			}
        });

        btnTaoHopDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToaHDActionPerformed(evt);
            }

			private void btnToaHDActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				dispose();
				new AddCustomerFrame(maXe, nhanVien).setVisible(true);
				
			}
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnThoat)
                        .addGap(424, 424, 424)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenXe)
                            .addComponent(lblGiaXe)
                            .addComponent(lblLoaiXe)
                            .addComponent(lblSoPK)
                            .addComponent(lblMauXe)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnTaoHopDong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNuocSanXuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(287, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnThoat))
                .addGap(37, 37, 37)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTenXe)
                        .addGap(18, 18, 18)
                        .addComponent(lblGiaXe)
                        .addGap(18, 18, 18)
                        .addComponent(lblLoaiXe)
                        .addGap(18, 18, 18)
                        .addComponent(lblSoPK)
                        .addGap(18, 18, 18)
                        .addComponent(lblMauXe)
                        .addGap(18, 18, 18)
                        .addComponent(lblNuocSanXuat)
                        .addGap(36, 36, 36)
                        .addComponent(btnTaoHopDong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    	 dispose();
         new Home(nhanVien).setVisible(true);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BanHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BanHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BanHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BanHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BanHangFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoHopDong;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelHinhAnh;
    private javax.swing.JLabel lblGiaXe;
    private javax.swing.JLabel lblLoaiXe;
    private javax.swing.JLabel lblMauXe;
    private javax.swing.JLabel lblNuocSanXuat;
    private javax.swing.JLabel lblSoPK;
    private javax.swing.JLabel lblTenXe;
    private javax.swing.JTable tableXeMay;
    // End of variables declaration//GEN-END:variables
}
