/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Admin
 */
public class QuanLyNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        pnMainNVHC = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        btnThoatNVHC = new javax.swing.JButton();
        lbltieudeNVHC = new javax.swing.JLabel();
        btnThemNVHC = new javax.swing.JButton();
        btnXoaNVHC = new javax.swing.JButton();
        btnSuaNVHC = new javax.swing.JButton();
        btnLuuNVHC = new javax.swing.JButton();
        btnQuayLaiNVHC = new javax.swing.JButton();
        lblMaNVHC = new javax.swing.JLabel();
        txtmaNVHC = new javax.swing.JTextField();
        lbltenNVHC = new javax.swing.JLabel();
        txttenNVHC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblsoDTNVHC = new javax.swing.JLabel();
        txtsoDTNVHC = new javax.swing.JTextField();
        lblGioiTinhNVHC = new javax.swing.JLabel();
        radNamNVHC = new javax.swing.JRadioButton();
        radNuNVHC = new javax.swing.JRadioButton();
        lblDiaChiNVHC = new javax.swing.JLabel();
        txtDiaChiNVHC = new javax.swing.JTextField();
        lblEmailNVHC = new javax.swing.JLabel();
        txtEmailNVHC = new javax.swing.JTextField();
        lblChucVuNVHC = new javax.swing.JLabel();
        cboChucVuNVHC = new javax.swing.JComboBox<>();
        lblRoleNVHC = new javax.swing.JLabel();
        cboRoleNVHC = new javax.swing.JComboBox<>();
        lblPhongBanNVHC = new javax.swing.JLabel();
        txtPhongBanNVHC = new javax.swing.JTextField();
        lblTrinhDoNVHC = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblTimNVHC = new javax.swing.JLabel();
        txtTimNVHC = new javax.swing.JTextField();
        btnTimNVHC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNVHC = new javax.swing.JTable();
        pnNhanVienKT = new javax.swing.JPanel();
        btnThoatNVKT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMaNVKT = new javax.swing.JLabel();
        txtMaNVKT = new javax.swing.JTextField();
        lblTenNVKT = new javax.swing.JLabel();
        txtTenNVKT = new javax.swing.JTextField();
        lblSoDTNVKT = new javax.swing.JLabel();
        txtSoDTNVKT = new javax.swing.JTextField();
        lblDiaChiNVKT = new javax.swing.JLabel();
        txtDiaChiNVKT = new javax.swing.JTextField();
        lblGioiTinhNVKT = new javax.swing.JLabel();
        radNamNVKT = new javax.swing.JRadioButton();
        radNuNVKT = new javax.swing.JRadioButton();
        lblEmailNVKT = new javax.swing.JLabel();
        txtEmailNVKT = new javax.swing.JTextField();
        lblChucVuNVKT = new javax.swing.JLabel();
        cboChucVuNVKT = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblBacThoNVKT = new javax.swing.JLabel();
        cboBacThoNVKT = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboNamKinhNghiemNVKT = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        lbltimNVKT = new javax.swing.JLabel();
        txtTimNVKT = new javax.swing.JTextField();
        btnTimNVKT = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        talbeNVKT = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMainNVHC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThoatNVHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.png"))); // NOI18N
        btnThoatNVHC.setText("Thoát");

        lbltieudeNVHC.setBackground(new java.awt.Color(0, 204, 204));
        lbltieudeNVHC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbltieudeNVHC.setForeground(new java.awt.Color(0, 102, 102));
        lbltieudeNVHC.setText("Nhân Viên Hành Chánh");

        btnThemNVHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnThemNVHC.setText("Thêm");

        btnXoaNVHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoaNVHC.setText("Xóa");

        btnSuaNVHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fix.png"))); // NOI18N
        btnSuaNVHC.setText("Sửa");

        btnLuuNVHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnLuuNVHC.setText("Lưu");

        btnQuayLaiNVHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        btnQuayLaiNVHC.setText("Quay Lại");

        lblMaNVHC.setText("Mã Nhân Viên: ");

        txtmaNVHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaNVHCActionPerformed(evt);
            }
        });

        lbltenNVHC.setText("Tên Nhân Viên:");

        lblsoDTNVHC.setText("Số ĐT:");

        lblGioiTinhNVHC.setText("Giới Tính:");

        radNamNVHC.setText("Nam");

        radNuNVHC.setText("Nữ");

        lblDiaChiNVHC.setText("Địa Chỉ: ");

        lblEmailNVHC.setText("Email:");

        lblChucVuNVHC.setText("Chức Vụ:");

        cboChucVuNVHC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuc vu 1", "Chuc vu  2", "Chuc vu  3", "Chuc vu 4" }));

        lblRoleNVHC.setText("Role:");

        cboRoleNVHC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Role 1", "Role 2", "Role 3", "Role 4" }));

        lblPhongBanNVHC.setText("Phòng Ban:");

        lblTrinhDoNVHC.setText("Trình Độ:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trung Học", "Cao Đẳng", "Đại Học" }));

        lblTimNVHC.setText("Tìm Kiếm Nhân Viên");

        btnTimNVHC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-20.png"))); // NOI18N
        btnTimNVHC.setText("Tìm");

        javax.swing.GroupLayout pnMainNVHCLayout = new javax.swing.GroupLayout(pnMainNVHC);
        pnMainNVHC.setLayout(pnMainNVHCLayout);
        pnMainNVHCLayout.setHorizontalGroup(
            pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnThemNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btnXoaNVHC)
                        .addGap(43, 357, Short.MAX_VALUE)
                        .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(btnQuayLaiNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMainNVHCLayout.createSequentialGroup()
                                    .addComponent(lblPhongBanNVHC)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPhongBanNVHC))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMainNVHCLayout.createSequentialGroup()
                                    .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDiaChiNVHC)
                                        .addComponent(lblEmailNVHC)
                                        .addComponent(lblRoleNVHC))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDiaChiNVHC)
                                        .addComponent(txtEmailNVHC)
                                        .addComponent(cboRoleNVHC, 0, 191, Short.MAX_VALUE))))))
                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                        .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThoatNVHC)
                                .addGap(224, 224, 224)
                                .addComponent(lbltieudeNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                        .addComponent(lbltenNVHC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txttenNVHC))
                                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                        .addComponent(lblMaNVHC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtmaNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnMainNVHCLayout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addComponent(lblsoDTNVHC)
                                        .addGap(67, 67, 67))
                                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(120, 120, 120))
                                                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                                        .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(lblChucVuNVHC)
                                                            .addComponent(lblGioiTinhNVHC))
                                                        .addGap(18, 18, 18))
                                                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                                        .addComponent(lblTrinhDoNVHC)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                                        .addComponent(radNamNVHC)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(radNuNVHC))
                                                    .addComponent(txtsoDTNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cboChucVuNVHC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                                            .addGap(1, 1, 1)
                                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(btnSuaNVHC))))
                                .addGap(89, 89, 89)
                                .addComponent(btnLuuNVHC)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTimNVHC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTimNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(538, 538, 538)))
                .addGap(32, 32, 32))
        );
        pnMainNVHCLayout.setVerticalGroup(
            pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThoatNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltieudeNVHC))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                        .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblMaNVHC)
                                    .addComponent(txtmaNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblsoDTNVHC)
                                    .addComponent(txtsoDTNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbltenNVHC)
                                    .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblGioiTinhNVHC)
                                        .addComponent(radNamNVHC)
                                        .addComponent(radNuNVHC))))
                            .addComponent(txttenNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(lblChucVuNVHC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboChucVuNVHC))
                        .addGap(18, 18, 18)
                        .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTrinhDoNVHC)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuayLaiNVHC))
                            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTimNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTimNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTimNVHC))
                                .addGap(43, 43, 43)
                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThemNVHC)
                                    .addComponent(btnXoaNVHC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSuaNVHC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLuuNVHC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnMainNVHCLayout.createSequentialGroup()
                        .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnMainNVHCLayout.createSequentialGroup()
                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDiaChiNVHC)
                                    .addComponent(txtDiaChiNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmailNVHC)
                                    .addComponent(txtEmailNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnMainNVHCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRoleNVHC)
                                    .addComponent(cboRoleNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblPhongBanNVHC))
                            .addComponent(txtPhongBanNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tableNVHC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Số ĐT", "Địa Chỉ", "Email", "Chức Vụ", "Role", "Phòng Ban", "Trình Độ"
            }
        ));
        jScrollPane1.setViewportView(tableNVHC);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMainNVHC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pnMainNVHC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("NhanVienHanhChanh", jPanel2);

        pnNhanVienKT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnThoatNVKT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.png"))); // NOI18N
        btnThoatNVKT.setText("Thoát");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Nhân Viên Kỹ Thuật");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        lblMaNVKT.setText("Mã Nhân Viên:");

        lblTenNVKT.setText("Tên Nhân Viên:");

        lblSoDTNVKT.setText("Số ĐT:");

        lblDiaChiNVKT.setText("Địa Chỉ");

        lblGioiTinhNVKT.setText("Giới Tính");

        radNamNVKT.setText("Nam");

        radNuNVKT.setText("Nữ");

        lblEmailNVKT.setText("Email");

        lblChucVuNVKT.setText("Chức Vụ");

        cboChucVuNVKT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chức vụ 1", "Chức vụ  2", "Chức vụ 3", "Chức vụ  4" }));

        jLabel3.setText("Role");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Role 1", "Role 2", "Role 3", "Role 4" }));

        lblBacThoNVKT.setText("Bậc Thợ");

        cboBacThoNVKT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bậc 1", "Bậc 2", "Bậc 3", "Bậc 4" }));

        jLabel4.setText("Số Năm Kinh Nghiệm");

        cboNamKinhNghiemNVKT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton1.setText("Thêm");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        jButton2.setText("Xóa");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fix.png"))); // NOI18N
        jButton3.setText("Sửa");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        jButton4.setText("Lưu");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        jButton5.setText("Quay Lại");

        lbltimNVKT.setText("Tìm Nhân Viên Kỹ Thuật");

        btnTimNVKT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-20.png"))); // NOI18N
        btnTimNVKT.setText("Tìm");

        jSeparator3.setBackground(new java.awt.Color(51, 0, 0));

        talbeNVKT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Giới Tính", "Số ĐT", "Địa Chỉ", "Email", "Chức Vụ", "Role", "Bậc Thợ", "Số Năm KN"
            }
        ));
        jScrollPane2.setViewportView(talbeNVKT);

        javax.swing.GroupLayout pnNhanVienKTLayout = new javax.swing.GroupLayout(pnNhanVienKT);
        pnNhanVienKT.setLayout(pnNhanVienKTLayout);
        pnNhanVienKTLayout.setHorizontalGroup(
            pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnThoatNVKT)
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                        .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addComponent(lbltimNVKT)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTimNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(btnTimNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jButton3))))
                            .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addComponent(lblTenNVKT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTenNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addComponent(lblMaNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMaNVKT)))
                                .addGap(107, 107, 107)
                                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSoDTNVKT)
                                    .addComponent(lblGioiTinhNVKT)
                                    .addComponent(lblChucVuNVKT)
                                    .addComponent(lblBacThoNVKT))
                                .addGap(30, 30, 30)
                                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                                .addComponent(radNamNVKT)
                                                .addGap(18, 18, 18)
                                                .addComponent(radNuNVKT))
                                            .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cboChucVuNVKT, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cboBacThoNVKT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27))
                                    .addComponent(txtSoDTNVKT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboNamKinhNghiemNVKT, 0, 118, Short.MAX_VALUE))
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addComponent(lblDiaChiNVKT)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDiaChiNVKT))
                                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                        .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEmailNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(19, 19, 19)
                                        .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEmailNVKT)
                                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)))))
                .addGap(27, 27, 27))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2)
        );
        pnNhanVienKTLayout.setVerticalGroup(
            pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoatNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                        .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaNVKT)
                            .addComponent(txtMaNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDiaChiNVKT)
                            .addComponent(txtDiaChiNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTenNVKT)
                            .addComponent(txtTenNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailNVKT)
                            .addComponent(txtEmailNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboNamKinhNghiemNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                            .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtSoDTNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSoDTNVKT))
                            .addGap(18, 18, 18)
                            .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radNamNVKT)
                                .addComponent(radNuNVKT)
                                .addComponent(lblGioiTinhNVKT))
                            .addGap(29, 29, 29)
                            .addComponent(cboChucVuNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24)
                            .addComponent(cboBacThoNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnNhanVienKTLayout.createSequentialGroup()
                            .addComponent(lblChucVuNVKT)
                            .addGap(24, 24, 24)
                            .addComponent(lblBacThoNVKT))))
                .addGap(44, 44, 44)
                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltimNVKT)
                    .addComponent(txtTimNVKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimNVKT))
                .addGap(35, 35, 35)
                .addGroup(pnNhanVienKTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("NhanVienKyThuat", pnNhanVienKT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaNVHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaNVHCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaNVHCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuuNVHC;
    private javax.swing.JButton btnQuayLaiNVHC;
    private javax.swing.JButton btnSuaNVHC;
    private javax.swing.JButton btnThemNVHC;
    private javax.swing.JButton btnThoatNVHC;
    private javax.swing.JButton btnThoatNVKT;
    private javax.swing.JButton btnTimNVHC;
    private javax.swing.JButton btnTimNVKT;
    private javax.swing.JButton btnXoaNVHC;
    private javax.swing.JComboBox<String> cboBacThoNVKT;
    private javax.swing.JComboBox<String> cboChucVuNVHC;
    private javax.swing.JComboBox<String> cboChucVuNVKT;
    private javax.swing.JComboBox<String> cboNamKinhNghiemNVKT;
    private javax.swing.JComboBox<String> cboRoleNVHC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lblBacThoNVKT;
    private javax.swing.JLabel lblChucVuNVHC;
    private javax.swing.JLabel lblChucVuNVKT;
    private javax.swing.JLabel lblDiaChiNVHC;
    private javax.swing.JLabel lblDiaChiNVKT;
    private javax.swing.JLabel lblEmailNVHC;
    private javax.swing.JLabel lblEmailNVKT;
    private javax.swing.JLabel lblGioiTinhNVHC;
    private javax.swing.JLabel lblGioiTinhNVKT;
    private javax.swing.JLabel lblMaNVHC;
    private javax.swing.JLabel lblMaNVKT;
    private javax.swing.JLabel lblPhongBanNVHC;
    private javax.swing.JLabel lblRoleNVHC;
    private javax.swing.JLabel lblSoDTNVKT;
    private javax.swing.JLabel lblTenNVKT;
    private javax.swing.JLabel lblTimNVHC;
    private javax.swing.JLabel lblTrinhDoNVHC;
    private javax.swing.JLabel lblsoDTNVHC;
    private javax.swing.JLabel lbltenNVHC;
    private javax.swing.JLabel lbltieudeNVHC;
    private javax.swing.JLabel lbltimNVKT;
    private javax.swing.JPanel pnMainNVHC;
    private javax.swing.JPanel pnNhanVienKT;
    private javax.swing.JRadioButton radNamNVHC;
    private javax.swing.JRadioButton radNamNVKT;
    private javax.swing.JRadioButton radNuNVHC;
    private javax.swing.JRadioButton radNuNVKT;
    private javax.swing.JTable tableNVHC;
    private javax.swing.JTable talbeNVKT;
    private javax.swing.JTextField txtDiaChiNVHC;
    private javax.swing.JTextField txtDiaChiNVKT;
    private javax.swing.JTextField txtEmailNVHC;
    private javax.swing.JTextField txtEmailNVKT;
    private javax.swing.JTextField txtMaNVKT;
    private javax.swing.JTextField txtPhongBanNVHC;
    private javax.swing.JTextField txtSoDTNVKT;
    private javax.swing.JTextField txtTenNVKT;
    private javax.swing.JTextField txtTimNVHC;
    private javax.swing.JTextField txtTimNVKT;
    private javax.swing.JTextField txtmaNVHC;
    private javax.swing.JTextField txtsoDTNVHC;
    private javax.swing.JTextField txttenNVHC;
    // End of variables declaration//GEN-END:variables
}
