/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.Iterator;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import dao.DAO_LoaiXe;
import entity.LoaiXe;

/**
 *
 * @author Dragon
 */
public class QuanLyLoaiSanPham extends javax.swing.JFrame implements ActionListener,MouseListener {

	DefaultTableModel tableModel;
	List<LoaiXe> listLoaiXe;
	DAO_LoaiXe daoLoaiXe = new DAO_LoaiXe();
    /**
     * Creates new form QuanLyLoaiSanPham
     */
    public QuanLyLoaiSanPham() {
        initComponents();
        tableModel = (DefaultTableModel) tableQuanLyLoaiSanPham.getModel();
        showData();
        Khoa();
    }

    private void showData() {
    	listLoaiXe = daoLoaiXe.getalltbLoaiXe();
    	tableModel.setRowCount(0);
    	for(LoaiXe item: listLoaiXe) {
    		tableModel.addRow(new Object[] {item.getMaLoai(), item.getTenLoai()});
    	}
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThoat = new javax.swing.JButton();
        lblTitleQuanLyLoaiSanPham = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMaLoai = new javax.swing.JLabel();
        lblTenLoai = new javax.swing.JLabel();
        txtMaLoai = new javax.swing.JTextField();
        txtTenLoai = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuanLyLoaiSanPham = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/out.png"))); // NOI18N
        btnThoat.setText("Back");

        lblTitleQuanLyLoaiSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitleQuanLyLoaiSanPham.setText("QUẢN LÝ LOẠI SẢN PHẨM");

        lblMaLoai.setText("Mã Loại: ");

        lblTenLoai.setText("Tên Loại:");

        txtMaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLoaiActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        jButton2.setText("Xóa Trắng");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/fix.png"))); // NOI18N
        jButton4.setText("Sửa");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        jButton5.setText("Xóa");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        jButton6.setText("Lưu");

        tableQuanLyLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
//                {null, null},
//                {null, null},
//                {null, null},
//                {null, null}
            },
            new String [] {
                "Mã loại", "Tên loại"
            }
        ));
        jScrollPane1.setViewportView(tableQuanLyLoaiSanPham);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addGap(364, 364, 364)
                        .addComponent(lblTitleQuanLyLoaiSanPham)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(lblMaLoai))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButton3)
                                .addGap(125, 125, 125)
                                .addComponent(jButton4)
                                .addGap(112, 112, 112)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addComponent(jButton6)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTenLoai)
                                .addGap(18, 18, 18)
                                .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(202, 202, 202))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleQuanLyLoaiSanPham)
                    .addComponent(btnThoat))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenLoai)
                    .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaLoai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
      //  add event
        jButton2.addActionListener(this); // xoa trang
        jButton3.addActionListener(this); // them
        jButton4.addActionListener(this); // sửa
        jButton5.addActionListener(this); // xóa
        jButton6.addActionListener(this); // luu
        tableQuanLyLoaiSanPham.addMouseListener(this);
        
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtMaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLoaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyLoaiSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyLoaiSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMaLoai;
    private javax.swing.JLabel lblTenLoai;
    private javax.swing.JLabel lblTitleQuanLyLoaiSanPham;
    private javax.swing.JTable tableQuanLyLoaiSanPham;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtTenLoai;
    private int choose =0;
    // End of variables declaration//GEN-END:variables
    //mo khoa control
    private void Khoa() {
    	txtMaLoai.setEditable(false);
    	txtTenLoai.setEditable(false);
    	jButton2.setEnabled(false);
    	jButton4.setEnabled(false);
    	jButton5.setEnabled(false);
    	jButton6.setEnabled(false);
    	
    }
    //dong control
    
    // hàm  hỗ trợ
    
    	// --------------------xoa trang--------------------
    
    		private void xoaTrang() {
    			txtTenLoai.setText("");
//    			txtMaLoai.setText("");
    		}
    	// ------------------------ket thuc xoa trang--------------------
    		
    	//------------------------- kiem tra nhap	--------------------
    		private boolean kiemTraNhap() {
    			if(txtTenLoai.getText().trim().equals("")) {
    				txtTenLoai.requestFocus();
    				return false;
    			}
    			
    			return true;
    			
    		}
    		
    		
    	//------------------------- ket thuc kiem tra nhap----------------		
    
    // hàm  hỗ trợ
    
	@Override
	public void actionPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		Object o = e.getSource();
		if(o.equals(jButton3)) { // them
			choose = 1;
			if(jButton3.getText().equalsIgnoreCase("Them")) {
				xoaTrang();
				txtTenLoai.setEditable(true);
				jButton6.setEnabled(true); // luu 
				jButton2.setEnabled(true); // xoa trang
				jButton5.setEnabled(false); // xóa
				jButton4.setEnabled(false); // sửa
				jButton3.setText("Hủy");
			}
			else if(jButton3.getText().equalsIgnoreCase("Hủy")) {
				xoaTrang();
				Khoa();
				jButton3.setText("Them");
				
			}
			
			
		}
		
		// xoa trang
		if(o.equals(jButton2)) {
			xoaTrang();
		}
		
		// test
		// test
		
		
		// xóa 
		if (o.equals(jButton5)) { // xóa
			if(tableQuanLyLoaiSanPham.getSelectedRow()!=-1) {
				
				
				if(JOptionPane.showConfirmDialog(this, "Ban Có Muốn Xóa","Cảnh Bảo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
					int r = tableQuanLyLoaiSanPham.getSelectedRow();
					tableModel.removeRow(r); // xóa trong bảng
					daoLoaiXe.delete(Integer.parseInt(txtMaLoai.getText()));
					Khoa();
					jButton3.setEnabled(true);
					
				}
				else {
					Khoa();
					jButton3.setEnabled(true);
					
				}
				
				
				
			}

			
		} 
		// sửa 
		if(o.equals(jButton4)) {
			choose=2;
			if(tableQuanLyLoaiSanPham.getSelectedRow()!=-1) {
				if(jButton4.getText().equalsIgnoreCase("Sua")) {
					txtTenLoai.setEditable(true);
					jButton2.setEnabled(true);
					jButton3.setEnabled(false);
					jButton5.setEnabled(false);
					jButton6.setEnabled(true);
					jButton4.setText("Hủy");
					
				}
				else if(jButton4.getText().equalsIgnoreCase("Hủy")){
					xoaTrang();
					Khoa();
					
					
					jButton3.setEnabled(true);
					jButton4.setText("Sua");
					
					
				}
				
			}
			else {
				JOptionPane.showMessageDialog(this, "vui lòng chọn nhân viên để cập nhật");
			}
			
	
			
			
		}
		
//		// luu 
		if(o.equals(jButton6)) {
			if(choose==1) {
				if(kiemTraNhap()) {
					String tenLoai = txtTenLoai.getText();
					LoaiXe loaiXe = new LoaiXe(tenLoai);
					daoLoaiXe.create(loaiXe);
					showData();
					JOptionPane.showMessageDialog(this, "Thêm Thành Công");
					Khoa();
					jButton3.setText("Them");
				}
				else {
					JOptionPane.showMessageDialog(this, "Vui Lòng nhập đầy đủ thông tin");
				}
		
				
				
				
				
			}
			
		
			if(choose==2) {
				int ma = Integer.parseInt( txtMaLoai.getText());
				String tenLoai = txtTenLoai.getText();
				LoaiXe loaiXe = new LoaiXe(ma, tenLoai);
				daoLoaiXe.update(loaiXe);
				showData();
				JOptionPane.showMessageDialog(this, "Cập nhật thành công");
				Khoa();
				jButton3.setEnabled(true);
				
				jButton4.setText("Sua");
				
			
				
			}
			
		}
		
				
		
	}

		@Override
		public void mouseClicked(MouseEvent e) {
			// TODO Auto-generated method stub
			int row = tableQuanLyLoaiSanPham.getSelectedRow();
			txtMaLoai.setText(tableModel.getValueAt(row, 0).toString());
			txtTenLoai.setText(tableModel.getValueAt(row, 1).toString());
			txtTenLoai.setEditable(false);
			jButton5.setEnabled(true); // xóa
			jButton4.setEnabled(true); // sửa
			jButton3.setEnabled(false); // them
			
		}

		@Override
		public void mousePressed(MouseEvent e) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mouseReleased(MouseEvent e) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mouseEntered(MouseEvent e) {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void mouseExited(MouseEvent e) {
			// TODO Auto-generated method stub
			
		}
}
